using System;
using System.ComponentModel;

namespace HearbalKartDB.Entities
{
	/// <summary>
	///		The data structure representation of the 'Items' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IItems 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Items"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// ItemName : 
		/// </summary>
		System.String  ItemName  { get; set; }
		
		/// <summary>
		/// IsActive : 
		/// </summary>
		System.Boolean?  IsActive  { get; set; }
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		System.DateTime?  CreatedDate  { get; set; }
		
		/// <summary>
		/// Modifieddate : 
		/// </summary>
		System.DateTime?  Modifieddate  { get; set; }
		
		/// <summary>
		/// DeletedDate : 
		/// </summary>
		System.DateTime?  DeletedDate  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _itemPurchaseItemId
		/// </summary>	
		TList<ItemPurchase> ItemPurchaseCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _prodTableItemId
		/// </summary>	
		TList<ProdTable> ProdTableCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _itemSellItemId
		/// </summary>	
		TList<ItemSell> ItemSellCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _orderDetailsItemId
		/// </summary>	
		TList<OrderDetails> OrderDetailsCollection {  get;  set;}	

		#endregion Data Properties

	}
}


