
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file OrderDetails.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using HearbalKartDB.Entities.Validation;
#endregion

namespace HearbalKartDB.Entities
{
	///<summary>
	/// An object representation of the 'OrderDetails' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class OrderDetailsBase : EntityBase, IOrderDetails, IEntityId<OrderDetailsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private OrderDetailsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private OrderDetailsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private OrderDetailsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<OrderDetails> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event OrderDetailsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event OrderDetailsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="OrderDetailsBase"/> instance.
		///</summary>
		public OrderDetailsBase()
		{
			this.entityData = new OrderDetailsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="OrderDetailsBase"/> instance.
		///</summary>
		///<param name="_orderId"></param>
		///<param name="_customerId"></param>
		///<param name="_itemId"></param>
		///<param name="_amount"></param>
		///<param name="_isActive"></param>
		///<param name="_createdDate"></param>
		///<param name="_modifiedDate"></param>
		///<param name="_deletedDate"></param>
		public OrderDetailsBase(System.Int32? _orderId, System.Int32? _customerId, System.Int32? _itemId, 
			System.Int64? _amount, System.Boolean? _isActive, System.DateTime? _createdDate, System.DateTime? _modifiedDate, 
			System.DateTime? _deletedDate)
		{
			this.entityData = new OrderDetailsEntityData();
			this.backupData = null;

			this.OrderId = _orderId;
			this.CustomerId = _customerId;
			this.ItemId = _itemId;
			this.Amount = _amount;
			this.IsActive = _isActive;
			this.CreatedDate = _createdDate;
			this.ModifiedDate = _modifiedDate;
			this.DeletedDate = _deletedDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="OrderDetails"/> instance.
		///</summary>
		///<param name="_orderId"></param>
		///<param name="_customerId"></param>
		///<param name="_itemId"></param>
		///<param name="_amount"></param>
		///<param name="_isActive"></param>
		///<param name="_createdDate"></param>
		///<param name="_modifiedDate"></param>
		///<param name="_deletedDate"></param>
		public static OrderDetails CreateOrderDetails(System.Int32? _orderId, System.Int32? _customerId, System.Int32? _itemId, 
			System.Int64? _amount, System.Boolean? _isActive, System.DateTime? _createdDate, System.DateTime? _modifiedDate, 
			System.DateTime? _deletedDate)
		{
			OrderDetails newOrderDetails = new OrderDetails();
			newOrderDetails.OrderId = _orderId;
			newOrderDetails.CustomerId = _customerId;
			newOrderDetails.ItemId = _itemId;
			newOrderDetails.Amount = _amount;
			newOrderDetails.IsActive = _isActive;
			newOrderDetails.CreatedDate = _createdDate;
			newOrderDetails.ModifiedDate = _modifiedDate;
			newOrderDetails.DeletedDate = _deletedDate;
			return newOrderDetails;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(OrderDetailsColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the OrderId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? OrderId
		{
			get
			{
				return this.entityData.OrderId; 
			}
			
			set
			{
				if (this.entityData.OrderId == value)
					return;
				
                OnPropertyChanging("OrderId");                    
				OnColumnChanging(OrderDetailsColumn.OrderId, this.entityData.OrderId);
				this.entityData.OrderId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.OrderId, this.entityData.OrderId);
				OnPropertyChanged("OrderId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CustomerId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? CustomerId
		{
			get
			{
				return this.entityData.CustomerId; 
			}
			
			set
			{
				if (this.entityData.CustomerId == value)
					return;
				
                OnPropertyChanging("CustomerId");                    
				OnColumnChanging(OrderDetailsColumn.CustomerId, this.entityData.CustomerId);
				this.entityData.CustomerId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.CustomerId, this.entityData.CustomerId);
				OnPropertyChanged("CustomerId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ItemId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ItemId
		{
			get
			{
				return this.entityData.ItemId; 
			}
			
			set
			{
				if (this.entityData.ItemId == value)
					return;
				
                OnPropertyChanging("ItemId");                    
				OnColumnChanging(OrderDetailsColumn.ItemId, this.entityData.ItemId);
				this.entityData.ItemId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.ItemId, this.entityData.ItemId);
				OnPropertyChanged("ItemId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Amount property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? Amount
		{
			get
			{
				return this.entityData.Amount; 
			}
			
			set
			{
				if (this.entityData.Amount == value)
					return;
				
                OnPropertyChanging("Amount");                    
				OnColumnChanging(OrderDetailsColumn.Amount, this.entityData.Amount);
				this.entityData.Amount = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.Amount, this.entityData.Amount);
				OnPropertyChanged("Amount");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsActive property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? IsActive
		{
			get
			{
				return this.entityData.IsActive; 
			}
			
			set
			{
				if (this.entityData.IsActive == value)
					return;
				
                OnPropertyChanging("IsActive");                    
				OnColumnChanging(OrderDetailsColumn.IsActive, this.entityData.IsActive);
				this.entityData.IsActive = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.IsActive, this.entityData.IsActive);
				OnPropertyChanged("IsActive");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CreatedDate
		{
			get
			{
				return this.entityData.CreatedDate; 
			}
			
			set
			{
				if (this.entityData.CreatedDate == value)
					return;
				
                OnPropertyChanging("CreatedDate");                    
				OnColumnChanging(OrderDetailsColumn.CreatedDate, this.entityData.CreatedDate);
				this.entityData.CreatedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.CreatedDate, this.entityData.CreatedDate);
				OnPropertyChanged("CreatedDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ModifiedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ModifiedDate
		{
			get
			{
				return this.entityData.ModifiedDate; 
			}
			
			set
			{
				if (this.entityData.ModifiedDate == value)
					return;
				
                OnPropertyChanging("ModifiedDate");                    
				OnColumnChanging(OrderDetailsColumn.ModifiedDate, this.entityData.ModifiedDate);
				this.entityData.ModifiedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.ModifiedDate, this.entityData.ModifiedDate);
				OnPropertyChanged("ModifiedDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DeletedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? DeletedDate
		{
			get
			{
				return this.entityData.DeletedDate; 
			}
			
			set
			{
				if (this.entityData.DeletedDate == value)
					return;
				
                OnPropertyChanging("DeletedDate");                    
				OnColumnChanging(OrderDetailsColumn.DeletedDate, this.entityData.DeletedDate);
				this.entityData.DeletedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OrderDetailsColumn.DeletedDate, this.entityData.DeletedDate);
				OnPropertyChanged("DeletedDate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Customers"/>.
		/// </summary>
		/// <value>The source Customers for CustomerId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Customers CustomerIdSource
      	{
            get { return entityData.CustomerIdSource; }
            set { entityData.CustomerIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Items"/>.
		/// </summary>
		/// <value>The source Items for ItemId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Items ItemIdSource
      	{
            get { return entityData.ItemIdSource; }
            set { entityData.ItemIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Orders"/>.
		/// </summary>
		/// <value>The source Orders for OrderId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Orders OrderIdSource
      	{
            get { return entityData.OrderIdSource; }
            set { entityData.OrderIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "OrderDetails"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "OrderId", "CustomerID", "ItemID", "Amount", "ISActive", "CreatedDate", "ModifiedDate", "DeletedDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as OrderDetailsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (OrderDetails) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<OrderDetails>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as OrderDetails);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed OrderDetails Entity 
		///</summary>
		protected virtual OrderDetails Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			OrderDetails copy = new OrderDetails();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.OrderId = this.OrderId;
				copy.CustomerId = this.CustomerId;
				copy.ItemId = this.ItemId;
				copy.Amount = this.Amount;
				copy.IsActive = this.IsActive;
				copy.CreatedDate = this.CreatedDate;
				copy.ModifiedDate = this.ModifiedDate;
				copy.DeletedDate = this.DeletedDate;
			
			if (this.CustomerIdSource != null && existingCopies.Contains(this.CustomerIdSource))
				copy.CustomerIdSource = existingCopies[this.CustomerIdSource] as Customers;
			else
				copy.CustomerIdSource = MakeCopyOf(this.CustomerIdSource, existingCopies) as Customers;
			if (this.ItemIdSource != null && existingCopies.Contains(this.ItemIdSource))
				copy.ItemIdSource = existingCopies[this.ItemIdSource] as Items;
			else
				copy.ItemIdSource = MakeCopyOf(this.ItemIdSource, existingCopies) as Items;
			if (this.OrderIdSource != null && existingCopies.Contains(this.OrderIdSource))
				copy.OrderIdSource = existingCopies[this.OrderIdSource] as Orders;
			else
				copy.OrderIdSource = MakeCopyOf(this.OrderIdSource, existingCopies) as Orders;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed OrderDetails Entity 
		///</summary>
		public virtual OrderDetails Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed OrderDetails Entity which is a deep copy of the current entity.
		///</summary>
		public virtual OrderDetails DeepCopy()
		{
			return EntityHelper.Clone<OrderDetails>(this as OrderDetails);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as OrderDetailsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new OrderDetailsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as OrderDetailsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(OrderDetailsColumn column)
		{
			switch(column)
			{
					case OrderDetailsColumn.Id:
					return entityData.Id != _originalData.Id;
					case OrderDetailsColumn.OrderId:
					return entityData.OrderId != _originalData.OrderId;
					case OrderDetailsColumn.CustomerId:
					return entityData.CustomerId != _originalData.CustomerId;
					case OrderDetailsColumn.ItemId:
					return entityData.ItemId != _originalData.ItemId;
					case OrderDetailsColumn.Amount:
					return entityData.Amount != _originalData.Amount;
					case OrderDetailsColumn.IsActive:
					return entityData.IsActive != _originalData.IsActive;
					case OrderDetailsColumn.CreatedDate:
					return entityData.CreatedDate != _originalData.CreatedDate;
					case OrderDetailsColumn.ModifiedDate:
					return entityData.ModifiedDate != _originalData.ModifiedDate;
					case OrderDetailsColumn.DeletedDate:
					return entityData.DeletedDate != _originalData.DeletedDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< OrderDetailsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.OrderId != _originalData.OrderId;
			result = result || entityData.CustomerId != _originalData.CustomerId;
			result = result || entityData.ItemId != _originalData.ItemId;
			result = result || entityData.Amount != _originalData.Amount;
			result = result || entityData.IsActive != _originalData.IsActive;
			result = result || entityData.CreatedDate != _originalData.CreatedDate;
			result = result || entityData.ModifiedDate != _originalData.ModifiedDate;
			result = result || entityData.DeletedDate != _originalData.DeletedDate;
			return result;
		}	
		
		///<summary>
		///  Returns a OrderDetails Entity with the original data.
		///</summary>
		public OrderDetails GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateOrderDetails(
				_originalData.OrderId,
				_originalData.CustomerId,
				_originalData.ItemId,
				_originalData.Amount,
				_originalData.IsActive,
				_originalData.CreatedDate,
				_originalData.ModifiedDate,
				_originalData.DeletedDate
				);
				
			return (OrderDetails)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="OrderDetailsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is OrderDetailsBase)
				return ValueEquals(this, (OrderDetailsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="OrderDetailsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.OrderId == null) ? string.Empty : this.OrderId.ToString()).GetHashCode() ^ 
					((this.CustomerId == null) ? string.Empty : this.CustomerId.ToString()).GetHashCode() ^ 
					((this.ItemId == null) ? string.Empty : this.ItemId.ToString()).GetHashCode() ^ 
					((this.Amount == null) ? string.Empty : this.Amount.ToString()).GetHashCode() ^ 
					((this.IsActive == null) ? string.Empty : this.IsActive.ToString()).GetHashCode() ^ 
					((this.CreatedDate == null) ? string.Empty : this.CreatedDate.ToString()).GetHashCode() ^ 
					((this.ModifiedDate == null) ? string.Empty : this.ModifiedDate.ToString()).GetHashCode() ^ 
					((this.DeletedDate == null) ? string.Empty : this.DeletedDate.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="OrderDetailsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(OrderDetailsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="OrderDetailsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="OrderDetailsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="OrderDetailsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(OrderDetailsBase Object1, OrderDetailsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.OrderId != null && Object2.OrderId != null )
			{
				if (Object1.OrderId != Object2.OrderId)
					equal = false;
			}
			else if (Object1.OrderId == null ^ Object2.OrderId == null )
			{
				equal = false;
			}
			if ( Object1.CustomerId != null && Object2.CustomerId != null )
			{
				if (Object1.CustomerId != Object2.CustomerId)
					equal = false;
			}
			else if (Object1.CustomerId == null ^ Object2.CustomerId == null )
			{
				equal = false;
			}
			if ( Object1.ItemId != null && Object2.ItemId != null )
			{
				if (Object1.ItemId != Object2.ItemId)
					equal = false;
			}
			else if (Object1.ItemId == null ^ Object2.ItemId == null )
			{
				equal = false;
			}
			if ( Object1.Amount != null && Object2.Amount != null )
			{
				if (Object1.Amount != Object2.Amount)
					equal = false;
			}
			else if (Object1.Amount == null ^ Object2.Amount == null )
			{
				equal = false;
			}
			if ( Object1.IsActive != null && Object2.IsActive != null )
			{
				if (Object1.IsActive != Object2.IsActive)
					equal = false;
			}
			else if (Object1.IsActive == null ^ Object2.IsActive == null )
			{
				equal = false;
			}
			if ( Object1.CreatedDate != null && Object2.CreatedDate != null )
			{
				if (Object1.CreatedDate != Object2.CreatedDate)
					equal = false;
			}
			else if (Object1.CreatedDate == null ^ Object2.CreatedDate == null )
			{
				equal = false;
			}
			if ( Object1.ModifiedDate != null && Object2.ModifiedDate != null )
			{
				if (Object1.ModifiedDate != Object2.ModifiedDate)
					equal = false;
			}
			else if (Object1.ModifiedDate == null ^ Object2.ModifiedDate == null )
			{
				equal = false;
			}
			if ( Object1.DeletedDate != null && Object2.DeletedDate != null )
			{
				if (Object1.DeletedDate != Object2.DeletedDate)
					equal = false;
			}
			else if (Object1.DeletedDate == null ^ Object2.DeletedDate == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((OrderDetailsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static OrderDetailsComparer GetComparer()
        {
            return new OrderDetailsComparer();
        }
        */

        // Comparer delegates back to OrderDetails
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(OrderDetails rhs, OrderDetailsColumn which)
        {
            switch (which)
            {
            	
            	
            	case OrderDetailsColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.OrderId:
            		return this.OrderId.Value.CompareTo(rhs.OrderId.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.CustomerId:
            		return this.CustomerId.Value.CompareTo(rhs.CustomerId.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.ItemId:
            		return this.ItemId.Value.CompareTo(rhs.ItemId.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.Amount:
            		return this.Amount.Value.CompareTo(rhs.Amount.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.IsActive:
            		return this.IsActive.Value.CompareTo(rhs.IsActive.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.CreatedDate:
            		return this.CreatedDate.Value.CompareTo(rhs.CreatedDate.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.ModifiedDate:
            		return this.ModifiedDate.Value.CompareTo(rhs.ModifiedDate.Value);
            		
            		                 
            	
            	
            	case OrderDetailsColumn.DeletedDate:
            		return this.DeletedDate.Value.CompareTo(rhs.DeletedDate.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<OrderDetailsKey> Members
		
		// member variable for the EntityId property
		private OrderDetailsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual OrderDetailsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new OrderDetailsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("OrderDetails")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- Id: {0}{9}- OrderId: {1}{9}- CustomerId: {2}{9}- ItemId: {3}{9}- Amount: {4}{9}- IsActive: {5}{9}- CreatedDate: {6}{9}- ModifiedDate: {7}{9}- DeletedDate: {8}{9}{11}", 
				this.Id,
				(this.OrderId == null) ? string.Empty : this.OrderId.ToString(),
				(this.CustomerId == null) ? string.Empty : this.CustomerId.ToString(),
				(this.ItemId == null) ? string.Empty : this.ItemId.ToString(),
				(this.Amount == null) ? string.Empty : this.Amount.ToString(),
				(this.IsActive == null) ? string.Empty : this.IsActive.ToString(),
				(this.CreatedDate == null) ? string.Empty : this.CreatedDate.ToString(),
				(this.ModifiedDate == null) ? string.Empty : this.ModifiedDate.ToString(),
				(this.DeletedDate == null) ? string.Empty : this.DeletedDate.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'OrderDetails' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class OrderDetailsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "OrderDetails"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// OrderId : 
		/// </summary>
		public System.Int32? OrderId = null;
		
		/// <summary>
		/// CustomerID : 
		/// </summary>
		public System.Int32? CustomerId = null;
		
		/// <summary>
		/// ItemID : 
		/// </summary>
		public System.Int32? ItemId = null;
		
		/// <summary>
		/// Amount : 
		/// </summary>
		public System.Int64? Amount = null;
		
		/// <summary>
		/// ISActive : 
		/// </summary>
		public System.Boolean? IsActive = null;
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		public System.DateTime? CreatedDate = null;
		
		/// <summary>
		/// ModifiedDate : 
		/// </summary>
		public System.DateTime? ModifiedDate = null;
		
		/// <summary>
		/// DeletedDate : 
		/// </summary>
		public System.DateTime? DeletedDate = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Customers _customerIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Customers"/>.
		/// </summary>
		/// <value>The source Customers for CustomerId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Customers CustomerIdSource
      	{
            get { return this._customerIdSource; }
            set { this._customerIdSource = value; }
      	}
		private Items _itemIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Items"/>.
		/// </summary>
		/// <value>The source Items for ItemId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Items ItemIdSource
      	{
            get { return this._itemIdSource; }
            set { this._itemIdSource = value; }
      	}
		private Orders _orderIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Orders"/>.
		/// </summary>
		/// <value>The source Orders for OrderId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Orders OrderIdSource
      	{
            get { return this._orderIdSource; }
            set { this._orderIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			OrderDetailsEntityData _tmp = new OrderDetailsEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.OrderId = this.OrderId;
			_tmp.CustomerId = this.CustomerId;
			_tmp.ItemId = this.ItemId;
			_tmp.Amount = this.Amount;
			_tmp.IsActive = this.IsActive;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.ModifiedDate = this.ModifiedDate;
			_tmp.DeletedDate = this.DeletedDate;
			
			#region Source Parent Composite Entities
			if (this.CustomerIdSource != null)
				_tmp.CustomerIdSource = MakeCopyOf(this.CustomerIdSource) as Customers;
			if (this.ItemIdSource != null)
				_tmp.ItemIdSource = MakeCopyOf(this.ItemIdSource) as Items;
			if (this.OrderIdSource != null)
				_tmp.OrderIdSource = MakeCopyOf(this.OrderIdSource) as Orders;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			OrderDetailsEntityData _tmp = new OrderDetailsEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.OrderId = this.OrderId;
			_tmp.CustomerId = this.CustomerId;
			_tmp.ItemId = this.ItemId;
			_tmp.Amount = this.Amount;
			_tmp.IsActive = this.IsActive;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.ModifiedDate = this.ModifiedDate;
			_tmp.DeletedDate = this.DeletedDate;
			
			#region Source Parent Composite Entities
			if (this.CustomerIdSource != null && existingCopies.Contains(this.CustomerIdSource))
				_tmp.CustomerIdSource = existingCopies[this.CustomerIdSource] as Customers;
			else
				_tmp.CustomerIdSource = MakeCopyOf(this.CustomerIdSource, existingCopies) as Customers;
			if (this.ItemIdSource != null && existingCopies.Contains(this.ItemIdSource))
				_tmp.ItemIdSource = existingCopies[this.ItemIdSource] as Items;
			else
				_tmp.ItemIdSource = MakeCopyOf(this.ItemIdSource, existingCopies) as Items;
			if (this.OrderIdSource != null && existingCopies.Contains(this.OrderIdSource))
				_tmp.OrderIdSource = existingCopies[this.OrderIdSource] as Orders;
			else
				_tmp.OrderIdSource = MakeCopyOf(this.OrderIdSource, existingCopies) as Orders;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OrderDetailsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(OrderDetailsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OrderDetailsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(OrderDetailsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OrderDetailsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(OrderDetailsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				OrderDetailsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new OrderDetailsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OrderDetailsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(OrderDetailsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				OrderDetailsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new OrderDetailsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region OrderDetailsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="OrderDetails"/> object.
	/// </remarks>
	public class OrderDetailsEventArgs : System.EventArgs
	{
		private OrderDetailsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the OrderDetailsEventArgs class.
		///</summary>
		public OrderDetailsEventArgs(OrderDetailsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the OrderDetailsEventArgs class.
		///</summary>
		public OrderDetailsEventArgs(OrderDetailsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The OrderDetailsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="OrderDetailsColumn" />
		public OrderDetailsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all OrderDetails related events.
	///</summary>
	public delegate void OrderDetailsEventHandler(object sender, OrderDetailsEventArgs e);
	
	#region OrderDetailsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class OrderDetailsComparer : System.Collections.Generic.IComparer<OrderDetails>
	{
		OrderDetailsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:OrderDetailsComparer"/> class.
        /// </summary>
		public OrderDetailsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:OrderDetailsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public OrderDetailsComparer(OrderDetailsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="OrderDetails"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="OrderDetails"/> to compare.</param>
        /// <param name="b">The second <c>OrderDetails</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(OrderDetails a, OrderDetails b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(OrderDetails entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(OrderDetails a, OrderDetails b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public OrderDetailsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region OrderDetailsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="OrderDetails"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class OrderDetailsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the OrderDetailsKey class.
		/// </summary>
		public OrderDetailsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the OrderDetailsKey class.
		/// </summary>
		public OrderDetailsKey(OrderDetailsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the OrderDetailsKey class.
		/// </summary>
		public OrderDetailsKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private OrderDetailsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public OrderDetailsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region OrderDetailsColumn Enum
	
	/// <summary>
	/// Enumerate the OrderDetails columns.
	/// </summary>
	[Serializable]
	public enum OrderDetailsColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// OrderId : 
		/// </summary>
		[EnumTextValue("Order Id")]
		[ColumnEnum("OrderId", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		OrderId = 2,
		/// <summary>
		/// CustomerId : 
		/// </summary>
		[EnumTextValue("Customer Id")]
		[ColumnEnum("CustomerID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		CustomerId = 3,
		/// <summary>
		/// ItemId : 
		/// </summary>
		[EnumTextValue("Item Id")]
		[ColumnEnum("ItemID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ItemId = 4,
		/// <summary>
		/// Amount : 
		/// </summary>
		[EnumTextValue("Amount")]
		[ColumnEnum("Amount", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		Amount = 5,
		/// <summary>
		/// IsActive : 
		/// </summary>
		[EnumTextValue("Is Active")]
		[ColumnEnum("ISActive", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		IsActive = 6,
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		[EnumTextValue("Created Date")]
		[ColumnEnum("CreatedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreatedDate = 7,
		/// <summary>
		/// ModifiedDate : 
		/// </summary>
		[EnumTextValue("Modified Date")]
		[ColumnEnum("ModifiedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ModifiedDate = 8,
		/// <summary>
		/// DeletedDate : 
		/// </summary>
		[EnumTextValue("Deleted Date")]
		[ColumnEnum("DeletedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		DeletedDate = 9
	}//End enum

	#endregion OrderDetailsColumn Enum

} // end namespace
